-- Migration 018: Ireland, Netherlands, and Sweden monitoring source coverage
--
-- PURPOSE: Backfill active regulation_sources for the EU scan profiles that
-- still reported zero active sources in production health:
-- ireland_official_legal_scan, netherlands_official_legal_scan,
-- sweden_official_legal_scan.
--
-- SAFETY: Non-destructive. Upserts only known source IDs.

insert into public.regulation_sources (
  id,
  name,
  jurisdiction,
  region,
  country,
  source_url,
  source_type,
  scan_frequency,
  active,
  last_scanned_at,
  notes,
  reliability_level,
  preferred_extraction_method,
  config,
  ingestion_method,
  source_category,
  created_at,
  updated_at
) values
  (
    'src-ie-dpc-ai',
    'Irish DPC AI and data-protection materials',
    'Ireland',
    'Europe',
    'Ireland',
    'https://www.dataprotection.ie/en/news-media/latest-news',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Irish Data Protection Commission news and guidance source for AI, large language models, automated processing, and technology enforcement signals.',
    'high',
    'html_static',
    '{"maxItems":20,"authorityTypeHint":"Agency guidance","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["artificial intelligence","ai","large language model","algorithm","automated decision","grok"],"editorialNotes":["Official DPC source.","DPC materials remain distinct from AI Act implementing legislation unless linked to enacted texts."]}'::jsonb,
    'existing',
    'regulator',
    now(),
    now()
  ),
  (
    'src-ie-dete-ai',
    'Ireland DETE EU AI Act implementation',
    'Ireland',
    'Europe',
    'Ireland',
    'https://enterprise.gov.ie/en/what-we-do/innovation-research-development/artificial-intelligence/eu-ai-act/',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Department of Enterprise, Trade and Employment source for Ireland''s EU AI Act implementation, AI Office, and regulatory sandbox materials.',
    'high',
    'html_static',
    '{"maxItems":15,"authorityTypeHint":"Government policy","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["artificial intelligence","ai act","ai office","regulatory sandbox","regulation of artificial intelligence"],"editorialNotes":["Official DETE source.","Government implementation pages are authoritative policy context, not binding law unless they link to legislation."]}'::jsonb,
    'existing',
    'official',
    now(),
    now()
  ),
  (
    'src-ie-gov-ai',
    'gov.ie Irish AI policy materials',
    'Ireland',
    'Europe',
    'Ireland',
    'https://www.gov.ie/en/search/?q=artificial+intelligence',
    'static_page',
    'daily',
    true,
    null,
    'Official Irish Government portal search anchor for AI policy, public-sector guidance, and implementation announcements.',
    'high',
    'html_static',
    '{"maxItems":15,"authorityTypeHint":"Government policy","includeAnyTerms":["artificial intelligence","ai act","algorithm","automated decision"],"editorialNotes":["Official gov.ie source.","Use as a policy and implementation discovery anchor."]}'::jsonb,
    'existing',
    'official',
    now(),
    now()
  ),
  (
    'src-ie-newsapi-ai',
    'Ireland AI legal news discovery (NewsAPI)',
    'Ireland',
    'Europe',
    'Ireland',
    'https://newsapi.org/v2/everything?q=(%22artificial%20intelligence%22%20OR%20%22AI%20Act%22%20OR%20algorithm)%20AND%20(Ireland%20OR%20DPC%20OR%20DETE)%20AND%20(law%20OR%20regulation%20OR%20legal%20OR%20enforcement)&language=en&sortBy=publishedAt&pageSize=20&domains=irishtimes.com,businesspost.ie,rte.ie,reuters.com,politico.eu,euractiv.com,ft.com',
    'media_source',
    'hourly',
    true,
    null,
    'Discovery-only Irish AI legal news query restricted to reputable national and policy media.',
    'medium',
    'api',
    '{"apiProvider":"newsapi","sourceCategory":"media_discovery_source","maxItems":12,"allowedDomains":["irishtimes.com","businesspost.ie","rte.ie","reuters.com","politico.eu","euractiv.com","ft.com"]}'::jsonb,
    'existing',
    'media',
    now(),
    now()
  ),
  (
    'src-ie-gdelt-ai',
    'Ireland AI legal news corroboration (GDELT)',
    'Ireland',
    'Europe',
    'Ireland',
    'https://api.gdeltproject.org/api/v2/doc/doc?query=(%22artificial%20intelligence%22%20OR%20%22AI%20Act%22)%20AND%20Ireland%20AND%20(law%20OR%20regulation%20OR%20DPC)&mode=artlist&format=json&maxrecords=20',
    'discovery_source',
    'hourly',
    true,
    null,
    'Discovery and corroboration only; official confirmation remains required.',
    'medium',
    'api',
    '{"apiProvider":"gdelt","sourceCategory":"media_discovery_source","maxItems":12}'::jsonb,
    'existing',
    'media',
    now(),
    now()
  ),
  (
    'src-nl-ap-ai',
    'Dutch AP algorithms and AI materials',
    'Netherlands',
    'Europe',
    'Netherlands',
    'https://www.autoriteitpersoonsgegevens.nl/themas/algoritmes-ai',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Dutch Autoriteit Persoonsgegevens algorithms and AI topic hub for supervisory guidance and AI-risk materials.',
    'high',
    'html_static',
    '{"maxItems":20,"authorityTypeHint":"Agency guidance","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["algoritmes","kunstmatige intelligentie","ai-verordening","ai act","toezicht"],"editorialNotes":["Official AP source.","Supervisory guidance must remain distinct from binding legislation."]}'::jsonb,
    'existing',
    'regulator',
    now(),
    now()
  ),
  (
    'src-nl-rdi-ai',
    'Dutch RDI AI supervision materials',
    'Netherlands',
    'Europe',
    'Netherlands',
    'https://www.rdi.nl/onderwerpen/kunstmatige-intelligentie',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Dutch Rijksinspectie Digitale Infrastructuur materials for AI supervision and technical-market oversight.',
    'high',
    'html_static',
    '{"maxItems":15,"authorityTypeHint":"Agency guidance","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["kunstmatige intelligentie","ai-verordening","ai act","toezicht","markttoezicht"],"editorialNotes":["Official RDI source.","Technical supervision materials are not binding law unless tied to enacted measures."]}'::jsonb,
    'existing',
    'regulator',
    now(),
    now()
  ),
  (
    'src-nl-rijksoverheid-ai',
    'Rijksoverheid AI policy materials',
    'Netherlands',
    'Europe',
    'Netherlands',
    'https://www.rijksoverheid.nl/onderwerpen/kunstmatige-intelligentie',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Dutch government AI policy hub for national implementation, policy, and public-sector guidance.',
    'high',
    'html_static',
    '{"maxItems":15,"authorityTypeHint":"Government policy","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["kunstmatige intelligentie","ai-verordening","ai act","algoritme"],"editorialNotes":["Official Rijksoverheid source.","Policy materials remain soft law unless enacted."]}'::jsonb,
    'existing',
    'official',
    now(),
    now()
  ),
  (
    'src-nl-newsapi-ai',
    'Netherlands AI legal news discovery (NewsAPI)',
    'Netherlands',
    'Europe',
    'Netherlands',
    'https://newsapi.org/v2/everything?q=(%22kunstmatige%20intelligentie%22%20OR%20%22AI%20Act%22%20OR%20algoritme)%20AND%20(recht%20OR%20wet%20OR%20regulering%20OR%20toezicht%20OR%20AP%20OR%20RDI)&sortBy=publishedAt&pageSize=20&domains=nrc.nl,volkskrant.nl,fd.nl,tweakers.net,reuters.com,politico.eu,euractiv.com',
    'media_source',
    'hourly',
    true,
    null,
    'Discovery-only Dutch AI legal news query restricted to reputable national and policy media.',
    'medium',
    'api',
    '{"apiProvider":"newsapi","sourceCategory":"media_discovery_source","maxItems":12,"allowedDomains":["nrc.nl","volkskrant.nl","fd.nl","tweakers.net","reuters.com","politico.eu","euractiv.com"]}'::jsonb,
    'existing',
    'media',
    now(),
    now()
  ),
  (
    'src-nl-gdelt-ai',
    'Netherlands AI legal news corroboration (GDELT)',
    'Netherlands',
    'Europe',
    'Netherlands',
    'https://api.gdeltproject.org/api/v2/doc/doc?query=(%22kunstmatige%20intelligentie%22%20OR%20%22AI%20Act%22)%20AND%20(Netherlands%20OR%20Nederland)%20AND%20(recht%20OR%20wet%20OR%20regulering%20OR%20toezicht)&mode=artlist&format=json&maxrecords=20',
    'discovery_source',
    'hourly',
    true,
    null,
    'Discovery and corroboration only; official confirmation remains required.',
    'medium',
    'api',
    '{"apiProvider":"gdelt","sourceCategory":"media_discovery_source","maxItems":12}'::jsonb,
    'existing',
    'media',
    now(),
    now()
  ),
  (
    'src-se-imy-ai',
    'IMY (Integritetsskyddsmyndigheten) news',
    'Sweden',
    'Europe',
    'Sweden',
    'https://www.imy.se/nyheter/rss',
    'RSS',
    'daily',
    true,
    null,
    'Official Swedish DPA (IMY) RSS news feed, filtered deterministically for AI, AI Act, algorithms, biometrics, machine learning, and automated decisions.',
    'high',
    'rss',
    '{"maxItems":12,"includeAnyTerms":["artificiell intelligens","artificial intelligence","ai act","ai-förordningen","algoritm","deepfake","ansiktsigenkänning","maskininlärning","automatiserat beslut"],"rssScope":"imy_official_news_feed","editorialNotes":["Official IMY source.","Deterministic AI filtering remains mandatory because the news feed is broader than AI alone."]}'::jsonb,
    'existing',
    'regulator',
    now(),
    now()
  ),
  (
    'src-se-digg-ai',
    'DIGG AI Act and public-sector AI guidance',
    'Sweden',
    'Europe',
    'Sweden',
    'https://www.digg.se/kunskap-och-stod/eu-rattsakter/ai-forordningen',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Swedish Agency for Digital Government AI Act and public-sector AI guidance materials.',
    'high',
    'html_static',
    '{"maxItems":15,"authorityTypeHint":"Agency guidance","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["ai-förordningen","artificiell intelligens","generativ ai","offentlig förvaltning"],"editorialNotes":["Official DIGG source.","Public-sector guidance remains soft law unless tied to enacted measures."]}'::jsonb,
    'existing',
    'official',
    now(),
    now()
  ),
  (
    'src-se-regeringen-ai',
    'Swedish Government AI Act adaptation materials',
    'Sweden',
    'Europe',
    'Sweden',
    'https://regeringen.se/rattsliga-dokument/statens-offentliga-utredningar/2025/10/sou-2025101/',
    'regulator_page',
    'daily',
    true,
    null,
    'Official Swedish Government source for national adaptations to the EU AI Act and related inquiry materials.',
    'high',
    'html_static',
    '{"maxItems":15,"authorityTypeHint":"Proposed law","itemSelector":"main a[href]","linkSelector":"self","includeAnyTerms":["ai-förordningen","artificiell intelligens","marknadskontroll","sanktioner"],"editorialNotes":["Official Swedish Government source.","Inquiry reports and press releases must remain distinct from enacted law."]}'::jsonb,
    'existing',
    'official',
    now(),
    now()
  ),
  (
    'src-se-newsapi-ai',
    'Sweden AI legal news discovery (NewsAPI)',
    'Sweden',
    'Europe',
    'Sweden',
    'https://newsapi.org/v2/everything?q=(%22artificiell%20intelligens%22%20OR%20%22AI%20Act%22%20OR%20algoritm)%20AND%20(lag%20OR%20reglering%20OR%20juridik%20OR%20IMY%20OR%20DIGG)&sortBy=publishedAt&pageSize=20&domains=svd.se,di.se,dn.se,computersweden.se,reuters.com,politico.eu,euractiv.com',
    'media_source',
    'hourly',
    true,
    null,
    'Discovery-only Swedish AI legal news query restricted to reputable national and policy media.',
    'medium',
    'api',
    '{"apiProvider":"newsapi","sourceCategory":"media_discovery_source","maxItems":12,"allowedDomains":["svd.se","di.se","dn.se","computersweden.se","reuters.com","politico.eu","euractiv.com"]}'::jsonb,
    'existing',
    'media',
    now(),
    now()
  ),
  (
    'src-se-gdelt-ai',
    'Sweden AI legal news corroboration (GDELT)',
    'Sweden',
    'Europe',
    'Sweden',
    'https://api.gdeltproject.org/api/v2/doc/doc?query=(%22artificiell%20intelligens%22%20OR%20%22AI%20Act%22)%20AND%20(Sweden%20OR%20Sverige)%20AND%20(lag%20OR%20reglering%20OR%20IMY%20OR%20DIGG)&mode=artlist&format=json&maxrecords=20',
    'discovery_source',
    'hourly',
    true,
    null,
    'Discovery and corroboration only; official confirmation remains required.',
    'medium',
    'api',
    '{"apiProvider":"gdelt","sourceCategory":"media_discovery_source","maxItems":12}'::jsonb,
    'existing',
    'media',
    now(),
    now()
  )
on conflict (id) do update set
  name = excluded.name,
  jurisdiction = excluded.jurisdiction,
  region = excluded.region,
  country = excluded.country,
  source_url = excluded.source_url,
  source_type = excluded.source_type,
  scan_frequency = excluded.scan_frequency,
  active = excluded.active,
  notes = excluded.notes,
  reliability_level = excluded.reliability_level,
  preferred_extraction_method = excluded.preferred_extraction_method,
  config = excluded.config,
  ingestion_method = excluded.ingestion_method,
  source_category = excluded.source_category,
  updated_at = now();
