-- Register first-class International AI governance monitoring sources.
-- These sources are transnational soft-law / standards / governance sources.
-- They must not be treated as binding national law unless incorporated by a
-- jurisdiction-specific legal instrument.

insert into public.regulation_sources (
  id,
  name,
  jurisdiction,
  region,
  country,
  source_url,
  source_type,
  scan_frequency,
  active,
  last_scanned_at,
  notes,
  reliability_level,
  preferred_extraction_method,
  config,
  ingestion_method,
  source_category,
  created_at,
  updated_at
) values
(
  'src-unesco-ai-ethics',
  'UNESCO Recommendation on the Ethics of AI',
  'UNESCO',
  'International',
  'International',
  'https://www.unesco.org/en/artificial-intelligence/recommendation-ethics',
  'regulator_page',
  'weekly',
  true,
  null,
  'Official UNESCO AI ethics recommendation and implementation hub. Treat as international soft law and policy framework material, not binding national law unless incorporated domestically.',
  'high',
  'html_static',
  '{"maxItems":8,"authorityTypeHint":"Soft law","legalAreaHint":"AI governance","itemSelector":"main article, main li, main a[href*=''artificial-intelligence''], main a[href*=''recommendation''], main a[href*=''ethics'']","linkSelector":"a","excerptSelector":"p","dateSelector":"time, .date","editorialNotes":["Official UNESCO source.","International recommendation; not binding by default without domestic incorporation."]}'::jsonb,
  'existing',
  'official',
  now(),
  now()
),
(
  'src-un-ai-advisory-body',
  'UN High-Level Advisory Body on AI',
  'United Nations',
  'International',
  'International',
  'https://www.un.org/digital-emerging-technologies/ai-advisory-body',
  'regulator_page',
  'weekly',
  true,
  null,
  'Official United Nations AI Advisory Body page for international AI governance recommendations and follow-on governance architecture. Treat as policy report / governance framework material.',
  'high',
  'html_static',
  '{"maxItems":8,"authorityTypeHint":"Policy report","legalAreaHint":"AI governance","itemSelector":"main article, main li, main a[href*=''ai''], main a[href*=''artificial-intelligence''], main a[href$=''.pdf'']","linkSelector":"a","excerptSelector":"p","dateSelector":"time, .date","editorialNotes":["Official UN source.","International governance recommendation; not binding law by default."]}'::jsonb,
  'existing',
  'official',
  now(),
  now()
),
(
  'src-wipo-ai-ip',
  'WIPO Artificial Intelligence and Intellectual Property',
  'WIPO',
  'International',
  'International',
  'https://www.wipo.int/en/web/frontier-technologies/artificial-intelligence/index',
  'regulator_page',
  'weekly',
  true,
  null,
  'Official WIPO AI and IP clearing house / frontier technologies page for international AI intellectual-property policy monitoring.',
  'high',
  'html_static',
  '{"maxItems":8,"authorityTypeHint":"Policy report","legalAreaHint":"Intellectual property","itemSelector":"main article, main li, main a[href*=''artificial-intelligence''], main a[href*=''frontier-technologies''], main a[href*=''intellectual-property'']","linkSelector":"a","excerptSelector":"p","dateSelector":"time, .date","editorialNotes":["Official WIPO source.","Useful for international AI/IP policy monitoring and country instrument discovery."]}'::jsonb,
  'existing',
  'official',
  now(),
  now()
),
(
  'src-ieee-7000',
  'IEEE 7000-2021 ethical concerns in system design',
  'IEEE',
  'International',
  'International',
  'https://standards.ieee.org/standard/7000-2021.html',
  'standards_body',
  'weekly',
  true,
  null,
  'Official IEEE Standards Association metadata page for IEEE 7000-2021. Track public standard metadata and status only; do not reproduce paywalled standard text.',
  'high',
  'html_static',
  '{"maxItems":1,"authorityTypeHint":"Technical standard","legalAreaHint":"AI governance","editorialNotes":["Technical standard; official metadata only.","Paywalled full standard text may exist and should not be reproduced."]}'::jsonb,
  'existing',
  'official',
  now(),
  now()
),
(
  'src-international-newsapi-ai',
  'International AI legal major press (NewsAPI)',
  'International',
  'International',
  'International',
  'https://newsapi.org/v2/everything?q=(%22artificial%20intelligence%22%20OR%20%22AI%20governance%22%20OR%20%22AI%20standard%22)%20AND%20(OECD%20OR%20UNESCO%20OR%20ISO%20OR%20IEEE%20OR%20WIPO%20OR%20%22United%20Nations%22%20OR%20G7%20OR%20GPAI)%20AND%20(law%20OR%20legal%20OR%20regulation%20OR%20governance%20OR%20standard%20OR%20ethics)&language=en&sortBy=publishedAt&pageSize=20&domains=reuters.com,apnews.com,politico.eu,euractiv.com,ft.com,wsj.com,technologyreview.com,wired.com,iapp.org',
  'media_source',
  'hourly',
  true,
  null,
  'Discovery-only major-press NewsAPI query for international AI law, governance, standards, and soft-law signals. Serious media can publish to live news under publication rules, but cannot create verified legal authority without official confirmation.',
  'medium',
  'api',
  '{"apiProvider":"newsapi","sourceCategory":"media_discovery_source","maxItems":12,"allowedDomains":["reuters.com","apnews.com","politico.eu","euractiv.com","ft.com","wsj.com","technologyreview.com","wired.com","iapp.org"],"legalAreaHint":"AI governance"}'::jsonb,
  'existing',
  'media',
  now(),
  now()
),
(
  'src-international-gdelt-ai',
  'International AI legal news discovery (GDELT)',
  'International',
  'International',
  'International',
  'https://api.gdeltproject.org/api/v2/doc/doc?query=(%22AI%20governance%22%20OR%20%22artificial%20intelligence%22%20OR%20%22AI%20standard%22)%20(OECD%20OR%20UNESCO%20OR%20ISO%20OR%20IEEE%20OR%20WIPO%20OR%20%22United%20Nations%22%20OR%20G7%20OR%20GPAI)%20(law%20OR%20legal%20OR%20regulation%20OR%20governance%20OR%20ethics)&mode=artlist&format=json&maxrecords=20',
  'discovery_source',
  'hourly',
  true,
  null,
  'Discovery-only GDELT query used to spot international AI legal, governance, standards, and soft-law media signals. Items require official-source confirmation before authority use.',
  'medium',
  'api',
  '{"apiProvider":"gdelt","sourceCategory":"media_discovery_source","maxItems":12,"legalAreaHint":"AI governance"}'::jsonb,
  'existing',
  'media',
  now(),
  now()
)
on conflict (id) do update set
  name = excluded.name,
  jurisdiction = excluded.jurisdiction,
  region = excluded.region,
  country = excluded.country,
  source_url = excluded.source_url,
  source_type = excluded.source_type,
  scan_frequency = excluded.scan_frequency,
  active = excluded.active,
  notes = excluded.notes,
  reliability_level = excluded.reliability_level,
  preferred_extraction_method = excluded.preferred_extraction_method,
  config = excluded.config,
  ingestion_method = excluded.ingestion_method,
  source_category = excluded.source_category,
  updated_at = now();
