export const aiRegulationKeywordConfig = {
  aiTerms: [
    "artificial intelligence",
    " ai ",
    "ai ",
    " ai",
    "automated decision-making",
    "automated decisionmaking",
    "algorithmic decision-making",
    "algorithmic fairness",
    "algorithmic pricing",
    "algorithm",
    "algorithms",
    "machine learning",
    "generative ai",
    "foundation model",
    "foundation models",
    "large language model",
    "large language models",
    "biometric identification",
    "high-risk ai",
    "ai governance",
    "ai risk management",
    "ai management systems",
    "ai assurance",
    "ai security",
    "model governance",
    "algorithmic accountability",
    "conformity assessment",
    "responsible ai",
    "ai safety",
    "lifecycle management",
    "owasp aima",
    "iso/iec 42001",
    "iso 42001",
    "nist ai rmf",
    "ai risk",
    "model transparency",
    "algorithmic discrimination",
    "automated employment decision tool",
    "synthetic content",
    "deepfake",
    "ai act",
    "general-purpose ai",
    "intelligence artificielle",
    "modeles d'ia",
    "modeles ia",
    "intelligenza artificiale",
  ],
  regulatoryTerms: [
    "regulation",
    "regulatory",
    "rule",
    "rules",
    "notice",
    "notices",
    "guidance",
    "guidelines",
    "recommendation",
    "recommendations",
    "statement",
    "letter",
    "opinion",
    "opinions",
    "bill",
    "act",
    "law",
    "framework",
    "governance framework",
    "framework convention",
    "enforcement",
    "order",
    "complaint",
    "settlement",
    "press release",
    "consultation",
    "policy",
    "government",
    "agency",
    "commission",
    "parliament",
    "official",
    "oversight",
    "compliance",
    "governance",
    "public sector",
    "procurement",
    "transparency",
    "risk management",
    "management system",
    "management systems",
    "assurance",
  "best practice",
  "best practices",
  "best-practice",
  "best-practices",
    "lifecycle",
    "security by design",
    "data protection",
    "intergovernmental",
    "directive",
    "standard",
    "code of practice",
    "tool",
    "audit",
    "lawful basis",
    "legal basis",
    "rgpd",
    "conformity",
    "traceability",
    "circular letter",
    "industry letter",
    "advisory",
    "supervision",
    "supervisory",
    "fair lending",
    "adverse action",
    "biometrics",
    "ai office",
    "technical standard",
    "international standard",
    "owasp",
    "iso/iec",
    "nist",
  ],
  negativeTerms: [
    "podcast",
    "client alert",
    "newsletter",
    "conference announcement",
    "webinar",
    "event registration",
    "linkedin",
    "x.com",
    "tiktok",
    "instagram",
    "press release roundup",
    "sponsored",
  ],
  permissiveSourceContexts: [
    "federal register",
    "white house",
    "cnil",
    "oecd",
    "owasp",
    "iso",
    "ai office",
    "european commission",
    "eur-lex",
    "edpb",
    "edps",
    "ftc",
    "nist",
    "eeoc",
    "cfpb",
    "sec",
    "nydfs",
    "attorney general",
    "cppa",
    "ico",
    "council of europe",
    "government",
    "commission",
    "agency",
    "official",
  ],
} as const;
