export const aiLawNewsSourceTypes = [
  "official_source",
  "legal_regulatory_press",
  "tracker_database",
  "informal_discovery_source",
] as const;

export type AiLawNewsSourceType = (typeof aiLawNewsSourceTypes)[number];

export const aiLawNewsSourceReliabilityLevels = [
  "official_authority",
  "reputable_secondary",
  "tracker_secondary",
  "informal_discovery",
] as const;

export type AiLawNewsSourceReliability =
  (typeof aiLawNewsSourceReliabilityLevels)[number];

export interface AiLawNewsSourceConfig {
  id: string;
  name: string;
  url: string | null;
  sourceType: AiLawNewsSourceType;
  official: boolean;
  reliabilityLevel: AiLawNewsSourceReliability;
  region: "Europe" | "United States" | "International";
  topicCoverage: string[];
  scanFrequency: "daily" | "weekly" | "manual";
  active: boolean;
  paywallStatus: "public" | "paywalled" | "mixed" | "unknown";
  scrapingAllowed: boolean;
  manualOnly: boolean;
  lastChecked: string | null;
  parserStatus:
    | "ready"
    | "needs_parser"
    | "metadata_only"
    | "manual_review_only"
    | "inactive";
  notes: string;
}

const checkedAt = "2026-05-27T00:00:00.000Z";

export const aiLawNewsSourceConfigs: AiLawNewsSourceConfig[] = [
  {
    id: "news-official-new-york-courts-part-161",
    name: "New York Courts Part 161 and AI court rules",
    url: "https://ww2.nycourts.gov/rules/chiefadmin/161.shtml",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "United States",
    topicCoverage: [
      "New York",
      "court rules",
      "attorney filings",
      "professional responsibility",
      "AI in legal practice",
    ],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: true,
    lastChecked: checkedAt,
    parserStatus: "manual_review_only",
    notes:
      "Official New York State Unified Court System Part 161 page used for binding court-rule monitoring on AI use in court papers, including linked AO/75/2026 administrative-order metadata. Targeted parsing logic exists, but the court site currently returns runtime 403 responses from this monitor environment.",
  },
  {
    id: "news-official-eu-commission",
    name: "European Commission AI and Digital Strategy pages",
    url: "https://digital-strategy.ec.europa.eu/en/policies/regulatory-framework-ai",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["EU AI Act", "EU AI Office", "GPAI", "AI governance"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official EU source. Items can support legal authority after citation review and human publication.",
  },
  {
    id: "news-official-eu-commission-rss",
    name: "European Commission Highlighted News RSS",
    url: "https://commission.europa.eu/node/29665/rss_en",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["European Commission", "official news", "AI Act", "EU AI Office", "policy updates"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official European Commission RSS feed for highlighted news. It is broader than AI alone, so deterministic AI filtering remains mandatory before legal-intelligence use.",
  },
  {
    id: "news-official-edpb-rss",
    name: "EDPB official RSS",
    url: "https://www.edpb.europa.eu/rss.xml",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["EDPB", "AI Act", "automated decision-making", "profiling", "fundamental rights"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official EDPB RSS feed confirmed live from the public site. Items remain subject to deterministic AI filtering because the feed is broader than AI alone.",
  },
  {
    id: "news-official-curia-rss",
    name: "CURIA press releases RSS",
    url: "http://curia.europa.eu/site/rss.jsp?lang=en&secondLang=fr",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["CJEU", "case law", "data protection", "automated decision-making", "AI-related court signals"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official CURIA RSS feed for press releases. It is not AI-specific, so AI/legal filtering remains mandatory before any classification or case-law linkage.",
  },
  {
    id: "news-official-eurlex-proposals-rss",
    name: "EUR-Lex Commission proposals RSS",
    url: "https://eur-lex.europa.eu/EN/display-feed.rss?rssId=161",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["EUR-Lex", "Commission proposals", "AI Act", "EU legislative pipeline"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official EUR-Lex predefined RSS alert for Commission proposals and related documents. A useful official fast-feed layer, but still broad and therefore filter-dependent.",
  },
  {
    id: "news-official-eurlex-legislation-rss",
    name: "EUR-Lex legislation RSS",
    url: "https://eur-lex.europa.eu/EN/display-feed.rss?rssId=162",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["EUR-Lex", "Parliament and Council legislation", "AI Act", "binding law"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official EUR-Lex predefined RSS alert for Parliament and Council legislation. This supports faster official publication awareness but still needs AI-specific filtering and source verification.",
  },
  {
    id: "news-europe-newsapi-discovery",
    name: "European AI legal news discovery (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["European Union", "AI Act", "EU AI Office", "EDPB", "EDPS", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast discovery API across many publishers for European AI law signals. Results are lead material only and require official-source confirmation before legal-authority use.",
  },
  {
    id: "news-europe-major-press-newsapi",
    name: "Europe AI legal major press (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["European Union", "AI Act", "major newspapers", "legal press", "regulation"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Discovery-only NewsAPI lane restricted to major newspapers and policy press. Metadata only; never legal authority without official confirmation.",
  },
  {
    id: "news-europe-gdelt-discovery",
    name: "European AI legal news discovery (GDELT)",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "Europe",
    topicCoverage: ["European Union", "AI Act", "media discovery", "policy signals"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast global media discovery API for Europe-focused AI legal signals. Useful for currentness and alerting, but never authoritative by itself.",
  },
  {
    id: "news-official-france-cnil",
    name: "CNIL AI and Algorithms",
    url: "https://www.cnil.fr/fr/rss.xml",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["France", "CNIL", "AI Act", "AI guidance", "data protection"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official French DPA source used as a stable AI monitoring feed; still requires deterministic AI filtering because the RSS scope is broader than AI alone.",
  },
  {
    id: "news-official-france-legifrance",
    name: "Legifrance AI legal texts",
    url: "https://www.legifrance.gouv.fr/search/jorf",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["France", "laws", "decrees", "CNIL deliberations", "AI governance"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official French legislative database. A targeted parser now exists for result pages and text pages, but runtime server access may still be blocked and must be treated conservatively.",
  },
  {
    id: "news-official-france-judilibre",
    name: "Judilibre AI-related decisions",
    url: "https://api.piste.gouv.fr/cassation/judilibre/v1.0/search?query=intelligence%20artificielle&page_size=10",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["France", "case law", "judiciary", "AI", "algorithmic decisions"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official Judilibre API for French judicial decisions. Access still requires PISTE credentials and quota management, so runtime use depends on configured credentials.",
  },
  {
    id: "news-official-france-conseil-etat",
    name: "Conseil d'Etat artificial intelligence materials",
    url: "https://www.conseil-etat.fr/site/qui-sommes-nous/deontologie/charte-d-utilisation-de-l-intelligence-artificielle-au-sein-de-la-juridiction-administrative",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["France", "administrative justice", "AI governance", "public law"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official French administrative-judiciary source anchored to a dedicated AI charter page so targeted parsing can extract institutional AI material and linked jurisprudence references without treating the site home page as a stable feed.",
  },
  {
    id: "news-official-france-cour-cassation",
    name: "Cour de cassation artificial intelligence materials",
    url: "https://www.courdecassation.fr/publications/lettre-de-la-cour/ndeg7-septembre-2025/la-modernisation-de-la-cour-se-poursuit-3-rapports-rendus-publics",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["France", "judiciary", "AI and justice", "case law signals"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official top-court source anchored to a dedicated AI-report publication page; use only metadata and official pages, and distinguish institutional publications from judicial decisions.",
  },
  {
    id: "news-official-france-defenseur-droits",
    name: "Defender of Rights artificial intelligence materials",
    url: "https://www.defenseurdesdroits.fr/intelligence-artificielle-la-defenseure-des-droits-appelle-garantir-le-droit-de-la-non-376",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["France", "fundamental rights", "AI Act", "algorithms", "discrimination"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official independent-authority source anchored to a dedicated AI/non-discrimination page so targeted parsing can extract rights-protection material without treating the site home page as a stable AI feed.",
  },
  {
    id: "news-official-spain-aepd",
    name: "AEPD AI and Innovation",
    url: "https://www.aepd.es/areas-de-actuacion/innovacion-y-tecnologia",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Spain", "AEPD", "AI Act", "data protection", "guidance"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official Spanish DPA source used as the primary Spain lightweight official monitoring anchor for AI and technology publications.",
  },
  {
    id: "news-official-spain-aesia",
    name: "AESIA official materials",
    url: "https://www.aesia.gob.es/en",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Spain", "AESIA", "AI supervision", "governance"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official Spanish AI supervision agency site. Suitable for official governance monitoring, but not for aggressive high-frequency polling.",
  },
  {
    id: "news-official-spain-boe",
    name: "BOE AI legal texts",
    url: "https://www.boe.es/eli/es/rd/2023/08/22/729",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Spain", "BOE", "AI legal texts", "AESIA", "legislation"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official BOE legal-text source used for Spain's legal baseline and targeted AI-governance instruments.",
  },
  {
    id: "news-official-spain-moncloa",
    name: "La Moncloa AI governance materials",
    url: "https://www.lamoncloa.gob.es/consejodeministros/referencias/Paginas/2026/20260526-referencia-rueda-de-prensa-ministros.aspx",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Spain", "Council of Ministers", "AI governance", "draft law"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official Spanish government source anchored to the current AI-governance draft-law milestone for conservative legal monitoring.",
  },
  {
    id: "news-spain-newsapi-discovery",
    name: "Spain AI legal news discovery (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["Spain", "AEPD", "AESIA", "AI governance", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast discovery API across many publishers for Spanish AI law and policy signals. Results are lead material only and require official-source confirmation before legal-authority use.",
  },
  {
    id: "news-spain-major-press-newsapi",
    name: "Spain AI legal major press (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["Spain", "AI regulation", "major newspapers", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Discovery-only NewsAPI lane restricted to major newspapers and policy press relevant to Spain AI law. Metadata only; never legal authority without official confirmation.",
  },
  {
    id: "news-spain-gdelt-discovery",
    name: "Spain AI legal news discovery (GDELT)",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "Europe",
    topicCoverage: ["Spain", "AI governance", "media discovery", "policy signals"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast global media discovery API for Spain-focused AI legal signals. Useful for currentness and alerting, but never authoritative by itself.",
  },
  {
    id: "news-official-germany-bfdi-ai",
    name: "BfDI AI unit materials",
    url: "https://www.bfdi.bund.de/DE/BfDI/Inhalte/AufgabenReferate/Referat_28.html",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Germany", "BfDI", "AI", "data protection", "oversight"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official German BfDI AI unit source used as the primary Germany lightweight official monitoring anchor for AI oversight and data-protection posture.",
  },
  {
    id: "news-official-germany-bfdi-consultation",
    name: "BfDI AI-model consultation",
    url: "https://www.bfdi.bund.de/DE/BfDI/Inhalte/Konsultationsverfahren/KI-pbD/KI-pbD-Einleitung.html",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Germany", "BfDI", "AI models", "consultation", "data protection"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official BfDI consultation source on personal data in AI models. Treat as official guidance and consultation material, not binding legislation.",
  },
  {
    id: "news-official-germany-bundesregierung",
    name: "Federal Government AI Act implementation materials",
    url: "https://www.bundesregierung.de/breg-de/bundesregierung/bundeskanzleramt/umsetzung-ki-verordnung-2406638",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Germany", "AI Act implementation", "federal government", "authorities"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official Federal Government source used for Germany's AI Act implementation baseline and authority-designation monitoring.",
  },
  {
    id: "news-official-germany-bundestag",
    name: "Bundestag AI Act implementation materials",
    url: "https://www.bundestag.de/presse/hib/kurzmeldungen-1155112",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Germany", "Bundestag", "AI Act bill", "implementation"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official Bundestag parliamentary source used for Germany's AI Act implementation bill and parliamentary processing milestones.",
  },
  {
    id: "news-germany-newsapi-discovery",
    name: "Germany AI legal news discovery (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["Germany", "AI governance", "BfDI", "Bundestag", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast discovery API across many publishers for German AI law and policy signals. Results are lead material only and require official-source confirmation before legal-authority use.",
  },
  {
    id: "news-germany-major-press-newsapi",
    name: "Germany AI legal major press (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["Germany", "AI regulation", "major newspapers", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Discovery-only NewsAPI lane restricted to major newspapers and policy press relevant to Germany AI law. Metadata only; never legal authority without official confirmation.",
  },
  {
    id: "news-germany-gdelt-discovery",
    name: "Germany AI legal news discovery (GDELT)",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "Europe",
    topicCoverage: ["Germany", "AI governance", "media discovery", "policy signals"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast global media discovery API for Germany-focused AI legal signals. Useful for currentness and alerting, but never authoritative by itself.",
  },
  {
    id: "news-official-italy-garante",
    name: "Garante AI topic and decisions",
    url: "https://www.garanteprivacy.it/temi/intelligenza-artificiale",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Italy", "Garante", "AI", "data protection", "enforcement"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official Italian data-protection authority source used as the primary Italy lightweight official monitoring anchor for AI guidance, press actions, and supervisory signals.",
  },
  {
    id: "news-official-italy-agid",
    name: "AgID artificial intelligence materials",
    url: "https://www.agid.gov.it/it/notizie/linee-guida-su-ia-nella-pa-al-la-consultazione-pubblica-su-sviluppo-e-procurement",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Italy", "AgID", "public administration", "AI guidance"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official AgID source used for Italy's AI public-administration guidance and implementation monitoring.",
  },
  {
    id: "news-official-italy-normattiva",
    name: "Normattiva Italian AI legal texts",
    url: "https://www.normattiva.it/eli/id/2025/09/25/25G00143/CONSOLIDATED",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Italy", "Normattiva", "Law 132/2025", "AI legislation"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official Normattiva legal-text source used for Italy's AI law baseline and targeted article-level legal review.",
  },
  {
    id: "news-official-italy-dtd",
    name: "Digital Transformation Department AI materials",
    url: "https://innovazione.gov.it/argomenti/intelligenza-artificiale/",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "Europe",
    topicCoverage: ["Italy", "government strategy", "AI implementation", "digital transformation"],
    scanFrequency: "weekly",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Official Digital Transformation Department source used to monitor Italy's AI strategy, implementation, and coordination materials.",
  },
  {
    id: "news-italy-newsapi-discovery",
    name: "Italy AI legal news discovery (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["Italy", "AI governance", "Garante", "AgID", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast discovery API across many publishers for Italian AI law and policy signals. Results are lead material only and require official-source confirmation before legal-authority use.",
  },
  {
    id: "news-italy-major-press-newsapi",
    name: "Italy AI legal major press (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["Italy", "AI regulation", "major newspapers", "legal press"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Discovery-only NewsAPI lane restricted to major newspapers and policy press relevant to Italy AI law. Metadata only; never legal authority without official confirmation.",
  },
  {
    id: "news-italy-gdelt-discovery",
    name: "Italy AI legal news discovery (GDELT)",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "Europe",
    topicCoverage: ["Italy", "AI governance", "media discovery", "policy signals"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast global media discovery API for Italy-focused AI legal signals. Useful for currentness and alerting, but never authoritative by itself.",
  },
  {
    id: "news-official-federal-register",
    name: "Federal Register AI query",
    url: "https://www.federalregister.gov/",
    sourceType: "official_source",
    official: true,
    reliabilityLevel: "official_authority",
    region: "United States",
    topicCoverage: ["federal rulemaking", "agency notices", "executive materials"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Official U.S. federal source. Individual document type controls legal effect.",
  },
  {
    id: "news-iapp-trackers",
    name: "IAPP AI governance trackers and news",
    url: "https://iapp.org/",
    sourceType: "tracker_database",
    official: false,
    reliabilityLevel: "tracker_secondary",
    region: "International",
    topicCoverage: ["AI governance", "privacy", "state AI legislation"],
    scanFrequency: "manual",
    active: false,
    paywallStatus: "mixed",
    scrapingAllowed: false,
    manualOnly: true,
    lastChecked: null,
    parserStatus: "manual_review_only",
    notes:
      "Secondary tracker/news reference only. Verify every development with official sources before authority use.",
  },
  {
    id: "news-reuters-legal",
    name: "Reuters Legal / Technology / Regulation",
    url: "https://www.reuters.com/",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "International",
    topicCoverage: ["major litigation", "regulation", "enforcement", "policy"],
    scanFrequency: "manual",
    active: false,
    paywallStatus: "mixed",
    scrapingAllowed: false,
    manualOnly: true,
    lastChecked: null,
    parserStatus: "metadata_only",
    notes:
      "Media/legal press discovery only. Do not reproduce full article text or treat as legal authority.",
  },
  {
    id: "news-france-newsapi-discovery",
    name: "France AI legal news discovery (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["France", "AI legal news", "legal press", "policy reporting"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast discovery API across many publishers. Results are lead material only and require official-source confirmation before legal-authority use.",
  },
  {
    id: "news-france-major-press-newsapi",
    name: "France AI legal major press (NewsAPI)",
    url: "https://newsapi.org/v2/everything",
    sourceType: "legal_regulatory_press",
    official: false,
    reliabilityLevel: "reputable_secondary",
    region: "Europe",
    topicCoverage: ["France", "major newspapers", "AI legal news", "régulation", "justice"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "mixed",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Discovery-only NewsAPI lane restricted to major French and international newspapers covering French AI legal developments. Metadata only; never legal authority without official confirmation.",
  },
  {
    id: "news-france-gdelt-discovery",
    name: "France AI legal news discovery (GDELT)",
    url: "https://api.gdeltproject.org/api/v2/doc/doc",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "Europe",
    topicCoverage: ["France", "AI legal news", "policy signals", "media discovery"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "ready",
    notes:
      "Fast global media discovery API. Useful for currentness and alerting, but never authoritative by itself.",
  },
  {
    id: "news-ai-weekly",
    name: "AI Weekly / AI News Today",
    url: "https://aiweekly.co/ai-news-today",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "International",
    topicCoverage: ["AI policy leads", "AI law discovery", "regulatory news"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Discovery-only source. Leads require official-source confirmation and remain non-authoritative.",
  },
  {
    id: "news-global-policy-watch-ai",
    name: "Global Policy Watch AI category",
    url: "https://www.globalpolicywatch.com/category/artificial-intelligence/",
    sourceType: "informal_discovery_source",
    official: false,
    reliabilityLevel: "informal_discovery",
    region: "International",
    topicCoverage: ["AI regulation", "EU policy", "U.S. policy", "agency activity"],
    scanFrequency: "daily",
    active: true,
    paywallStatus: "public",
    scrapingAllowed: true,
    manualOnly: false,
    lastChecked: checkedAt,
    parserStatus: "needs_parser",
    notes:
      "Discovery-only legal/policy blog source. Official sources control before publication as legal authority.",
  },
];

export function getAiLawNewsSourceConfigByName(name: string) {
  const normalized = name.toLowerCase();
  return (
    aiLawNewsSourceConfigs.find(
      (source) =>
        source.name.toLowerCase() === normalized ||
        normalized.includes(source.name.toLowerCase()) ||
        source.name.toLowerCase().includes(normalized),
    ) ?? null
  );
}
